#!/bin/bash
set -euo pipefail

fver=$(. /etc/os-release && echo "${VERSION_ID}")
cosa_fver=$(curl -L https://raw.githubusercontent.com/coreos/coreos-assembler/main/Dockerfile | grep '^FROM ' | cut -f2 -d:)

# temporarily, use a COPR to get latest fzf
# NB: it says rawhide but the definition is the same for all releases
(cd /etc/yum.repos.d && curl -LO https://copr.fedorainfracloud.org/coprs/jlebon/fzf/repo/fedora-rawhide/jlebon-fzf-fedora-rawhide.repo)

# disable unneeded repos
(cd /etc/yum.repos.d &&
 sed -i -e 's/enabled=1/enabled=0/' ./fedora-cisco-openh264.repo &&
 if ls ./*-modular.repo; then sed -i -e 's/enabled=1/enabled=0/' ./*-modular.repo; fi)

# install packages
grep -v '^#' deps.txt | xargs dnf install -y

# chezmoi
(curl -Lo chezmoi https://github.com/twpayne/chezmoi/releases/download/v2.39.1/chezmoi-linux-amd64
 digest=$(sha256sum chezmoi | cut -f1 -d' ')
 [ "${digest}" = 8589264358009398bab4a84ff8b8d4a3c4df59c68ff705df3531582d7dfda33f ]
 chmod a+x chezmoi && mv chezmoi /usr/bin/
)

# cosa
if [ "${fver}" = "${cosa_fver}" ]; then
  (git clone https://github.com/coreos/coreos-assembler
   cd coreos-assembler
   ./build.sh configure_yum_repos
   ./build.sh install_rpms
   ./build.sh install_ocp_tools)
fi

# rpm-ostree test deps
(git clone https://github.com/coreos/rpm-ostree
 cd rpm-ostree
 ci/install-test-deps.sh)

# everything in the FCOS buildroot image
(git clone https://github.com/coreos/fedora-coreos-config
 cd fedora-coreos-config
 ci/buildroot/install-buildroot.sh)

# we want the host srv
rmdir /srv && ln -sT /run/host/srv /srv

# install rhsetup
cp rhsetup /usr/bin
