#!/bin/bash
set -euo pipefail

# install packages
grep -v '^#' deps.txt | xargs dnf install -y
grep -v '^#' builddeps.txt | xargs dnf builddep -y

# cosa
(git clone https://github.com/coreos/coreos-assembler
 cd coreos-assembler
 sed -i "s/frozendeps=.*/frozendeps=/" build.sh
 ./build.sh configure_yum_repos
 ./build.sh install_rpms)

# rpm-ostree test deps
(git clone https://github.com/coreos/rpm-ostree
 cd rpm-ostree
 ci/install-test-deps.sh)

# everything in the FCOS buildroot image
(git clone https://github.com/coreos/fedora-coreos-config
 cd fedora-coreos-config
 ci/buildroot/install-buildroot.sh)

# universal tags
(git clone https://github.com/universal-ctags/ctags
 cd ctags
 ./autogen.sh
 ./configure
 make -j8
 make install)

# we want the host srv
rmdir /srv && ln -sT /run/host/srv /srv

# install rhsetup
cp rhsetup /usr/bin
