#!/bin/bash
set -euo pipefail

# for helix
dnf copr enable -y varlad/helix

# install packages
grep -v '^#' deps.txt | xargs dnf install -y

fver=$(. /etc/os-release && echo "${VERSION_ID}")
cosa_fver=$(curl -L https://raw.githubusercontent.com/coreos/coreos-assembler/main/Dockerfile | grep '^FROM ' | cut -f2 -d:)

# cosa
if [ "${fver}" = "${cosa_fver}" ]; then
  (git clone https://github.com/coreos/coreos-assembler
   cd coreos-assembler
   ./build.sh configure_yum_repos
   ./build.sh install_rpms)
fi

# rpm-ostree test deps
(git clone https://github.com/coreos/rpm-ostree
 cd rpm-ostree
 ci/install-test-deps.sh)

# everything in the FCOS buildroot image
(git clone https://github.com/coreos/fedora-coreos-config
 cd fedora-coreos-config
 ci/buildroot/install-buildroot.sh)

# universal tags
(git clone https://github.com/universal-ctags/ctags
 cd ctags
 ./autogen.sh
 ./configure
 make -j8
 make install)

# we want the host srv
rmdir /srv && ln -sT /run/host/srv /srv

# install rhsetup
cp rhsetup /usr/bin
