#!/bin/bash
set -euo pipefail

# This tiny script sets up bits of the pet container that require the VPN.

cd /etc/pki/ca-trust/source/anchors
sudo curl -O https://password.corp.redhat.com/RH-IT-Root-CA.crt
sudo update-ca-trust extract

cd /etc/yum.repos.d/
sudo curl -L -O https://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-fedora.repo
sudo dnf install -y rhpkg

if [ -e /run/host/etc/krb5.conf.d/redhat ]; then
    sudo ln -s /run/host/etc/krb5.conf.d/redhat /etc/krb5.conf.d/
fi
